INSERT INTO public.category (category_id, name, level, parent_id) VALUES (15, 'Electronics & Technology', 1, null);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (16, 'Computers & Laptops', 2, 15);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (17, 'Smartphones', 3, 16);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (18, 'Phone Cases & Covers', 3, 16);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (19, 'Screen Protectors', 3, 16);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (20, 'Audio & Headphones', 2, 15);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (21, 'Headphones & Earphones', 3, 20);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (22, 'Bluetooth & Wireless Speakers', 3, 20);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (23, 'Home Audio Systems', 3, 20);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (24, 'Cameras & Photography', 2, 15);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (25, 'Digital Cameras', 2, 24);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (26, 'Camera Lenses', 2, 24);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (27, 'Camera Accessories', 2, 24);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (28, 'Smart Home Devices', 2, 15);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (29, 'Smart Lighting', 3, 28);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (30, 'Smart Thermostats', 3, 28);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (31, 'Security Cameras', 3, 28);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (32, 'Gaming', 2, 15);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (33, 'Gaming Consoles', 3, 32);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (34, 'Video Games', 3, 32);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (35, 'Gaming Accessories', 3, 32);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (36, 'Appliances', 2, 15);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (37, 'Kitchen Appliances', 3, 36);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (38, 'Home Appliances', 3, 36);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (39, 'Personal Care Appliances', 3, 36);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (40, 'Office & Stationery', 2, 15);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (41, 'Office Furniture', 3, 40);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (42, 'Stationery Supplies', 3, 40);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (43, 'Printers & Scanners', 3, 40);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (44, 'Health & Fitness', 2, 15);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (45, 'Fitness Trackers', 3, 44);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (46, 'Home Gym Equipment', 3, 44);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (47, 'Nutrition & Supplements', 3, 44);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (48, 'Fashion & Apparel', 2, 15);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (49, 'Men''s Clothing', 3, 48);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (50, 'Women''s Clothing', 3, 48);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (51, 'Shoes & Accessories', 3, 48);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (52, 'Books & Literature', 2, 15);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (53, 'Fiction', 3, 52);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (54, 'Non-Fiction', 3, 52);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (55, 'Children''s Books', 3, 52);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (56, 'Home & Furniture', 2, 15);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (57, 'Living Room Furniture', 3, 56);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (58, 'Bedroom Furniture', 3, 56);
INSERT INTO public.category (category_id, name, level, parent_id) VALUES (59, 'Home Decor', 3, 56);
