INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (1, 'Material', 'VARCHAR', false, 'Not Specified');
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (2, 'Rating', 'INTEGER', false, '0');
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (4, 'Resolution', 'VARCHAR', false, null);
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (5, 'Processor', 'VARCHAR', false, 'Unknown');
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (6, 'RAM', 'VARCHAR', false, '4GB');
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (8, 'ReleaseYear', 'INTEGER', false, null);
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (9, 'ScreenSize', 'FLOAT', false, null);
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (10, 'StorageCapacity', 'VARCHAR', false, '128GB');
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (12, 'Weight', 'FLOAT', false, null);
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (13, 'Brand', 'VARCHAR', false, 'Generic');
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (16, 'Language', 'VARCHAR', false, 'English');
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (17, 'Pages', 'INTEGER', false, null);
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (18, 'Manufacturer', 'VARCHAR', false, null);
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (19, 'Power', 'VARCHAR', false, null);
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (3, 'ISBN', 'VARCHAR', false, null);
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (7, 'Genre', 'VARCHAR', false, 'Not Specified');
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (20, 'Condition', 'VARCHAR', false, 'New');
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (11, 'Color', 'VARCHAR', false, null);
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (15, 'Size', 'VARCHAR', false, null);
INSERT INTO public.attribute (attribute_id, name, datatype, is_require, default_value) VALUES (14, 'Author', 'VARCHAR', false, 'Unknown');
