# docker compose file
version: '3.0'

services:

#
  authservice-database:
    build: ./Backend/AuthService/src/main/resources/db
    environment:
      POSTGRES_DB: shopee_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5433"
    volumes:
      - ./Backend/AuthService/src/main/resources/db:/AuthServiceDatabase
    command: -p 5433



  authservice:
    build: ./Backend/AuthService
    ports:
      - "8080:8080"
    volumes:
      - ./Backend/AuthService:/AuthService
      - ~/.aws:/root/.aws
    environment:
      - APP_NAME=Auth Service
      - spring.datasource.url= jdbc:postgresql://authservice-database:5433/shopee_db




  productservice-postgres-db:
    build: ./Backend/ProductService/src/main/resources/db
    environment:
      POSTGRES_DB: product_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./Backend/ProductService/src/main/resources/db:/ProductServiceDatabase



  productservice:
    build: ./Backend/ProductService
    ports:
      - "8081:8081"
    volumes:
      - ./Backend/ProductService:/ProductService
      - ~/.aws:/root/.aws
    environment:
      - spring.datasource.url=jdbc:postgresql://productservice-postgres-db:5432/product_db
    depends_on:
      - productservice-postgres-db



  apigateway:
    build: ./Backend/ApiGateway
    ports:
      - "8085:8085"
    volumes:
      - ./Backend/ApiGateway/:/apigateway
    depends_on:
      - productservice
      - authservice
    environment:
      SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://authservice:8080/
      SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: auth-route
      SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]: Path= /api/v1/auth/**,/api/v1/login/**,/login/oauth2/**
      SPRING_CLOUD_GATEWAY_ROUTES[1]_URI: http://productservice:8081/
      SPRING_CLOUD_GATEWAY_ROUTES[1]_ID: product-route
      SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]: Path=/api/v1/product/**,/api/v1/category/**,/api/v1/attribute_set/**,/api/v1/attribute_value/**,/api/v1/attribute/**

  frontend:
    build: ./Frontend
    ports:
      - "80:80"
    depends_on:
      - apigateway
    volumes:
      - ./Frontend:/frontend



