INSERT INTO users (id,
    first_name,
    last_name,
    username,
    password ,
    user_role,
    phone_number,
    gender,
    date_of_birth,
    postcode,
    address,
    city)

    VALUES (1,
    'Harry',
    'Le',
    'test123@test.com',
    '123456',
    'ADMIN',
    '0434444333',
    'Male',
    '1991/05/06',
    3000,
    '12 Bourke Street',
    'Melbourne');
