server:
  error:
    include-message: always
    include-binding-error: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shoppee_db
    username: postgres
    password: root

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem