server:
  error:
    include-message: always
    include-binding-error: always
hostname: localhost:8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shoppee_db
    username: postgres
    password: root

  mail:
    host: smtp.gmail.com
    username: shopeeclone.ecommerce.service@gmail.com
    password: stnlxsbkdvbrhwig
    properties:
      protocol: smtp
      smtp:
        port: 587
        auth: true
        starttls:
          enable: true
    debug: false
    template:
      registration: classpath:templates/mail_template/registration_template.html

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

registration: classpath:templates/mail_template/registration_template.html