spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/product_db
        username: postgres
        password: root

    data:
        rest:
            base-path: /api/v1

    jpa:
        show-sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
rsa:
    public-key: classpath:certs/public.pem

server:
    port: 8081

springfox:
    documentation:
        swagger-ui:
            enabled: true