server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/auth/**
        - id: product-route
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/product/**

servlet:
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
    allow-credentials: true