server:
  port: 8085
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: auth-route
          uri: http://localhost:8080/
          predicates:
            - Path=/api/v1/auth/**,/api/v1/login/**,/login/oauth2/**,/api/v1/logout

        - id: product-route
          uri: http://localhost:8081/
          predicates:
            - Path=/api/v1/product/**,/api/v1/category/**,/api/v1/attribute_set/**,/api/v1/attribute_value/**,/api/v1/attribute/**
servlet:
  cors:
    allowed-origins: http://localhost:3000
    allowed-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
    allow-credentials: true